"C:\Program Files\R\R-3.1.3\bin\x64\Rscript.exe" --vanilla Cow_Calf_Sub_Model_calculation_check-subwtsd-01-update.R > null
"C:\Program Files\R\R-3.1.3\bin\x64\Rscript.exe" --vanilla Cow_Calf_Sub_Model_calculation_check-subwtsd-02-update.R > null
"C:\Program Files\R\R-3.1.3\bin\x64\Rscript.exe" --vanilla Cow_Calf_Sub_Model_calculation_check-subwtsd-04-update.R > null
"C:\Program Files\R\R-3.1.3\bin\x64\Rscript.exe" --vanilla Cow_Calf_Sub_Model_calculation_check-subwtsd-05-update.R > null
"C:\Program Files\R\R-3.1.3\bin\x64\Rscript.exe" --vanilla Cow_Calf_Sub_Model_calculation_check-subwtsd-06-update.R > null
"C:\Program Files\R\R-3.1.3\bin\x64\Rscript.exe" --vanilla Cow_Calf_Sub_Model_calculation_check-subwtsd-07-update.R > null
"C:\Program Files\R\R-3.1.3\bin\x64\Rscript.exe" --vanilla Cow_Calf_Sub_Model_calculation_check-subwtsd-08-update.R > null
"C:\Program Files\R\R-3.1.3\bin\x64\Rscript.exe" --vanilla Cow_Calf_Sub_Model_calculation_check-subwtsd-09-update.R > null
"C:\Program Files\R\R-3.1.3\bin\x64\Rscript.exe" --vanilla Cow_Calf_Sub_Model_calculation_check-subwtsd-10-update.R > null
"C:\Program Files\R\R-3.1.3\bin\x64\Rscript.exe" --vanilla Cow_Calf_Sub_Model_calculation_check-subwtsd-11-update.R > null
"C:\Program Files\R\R-3.1.3\bin\x64\Rscript.exe" --vanilla Cow_Calf_Sub_Model_calculation_check-subwtsd-12-update.R > null
"C:\Program Files\R\R-3.1.3\bin\x64\Rscript.exe" --vanilla Cow_Calf_Sub_Model_calculation_check-subwtsd-13-update.R > null
"C:\Program Files\R\R-3.1.3\bin\x64\Rscript.exe" --vanilla Cow_Calf_Sub_Model_calculation_check-subwtsd-14-update.R > null
"C:\Program Files\R\R-3.1.3\bin\x64\Rscript.exe" --vanilla Cow_Calf_Sub_Model_calculation_check-subwtsd-16-update.R > null
"C:\Program Files\R\R-3.1.3\bin\x64\Rscript.exe" --vanilla Cow_Calf_Sub_Model_calculation_check-subwtsd-17-update.R > null
"C:\Program Files\R\R-3.1.3\bin\x64\Rscript.exe" --vanilla Cow_Calf_Sub_Model_calculation_check-subwtsd-18-update.R > null
